import os
import uuid
from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


def generate_application_pdf(fields: dict, output_dir: str, application_title: str = "Government Scheme Application", scheme_name: str | None = None, language_hint: str | None = None) -> str:
    os.makedirs(output_dir, exist_ok=True)
    output_path = os.path.join(output_dir, f"application_{uuid.uuid4().hex}.pdf")

    c = canvas.Canvas(output_path, pagesize=A4)
    width, height = A4

    y = height - 60
    c.setFont("Helvetica-Bold", 16)
    c.drawString(50, y, application_title)

    y -= 30
    c.setFont("Helvetica", 11)
    if scheme_name:
        c.drawString(50, y, f"Scheme: {scheme_name}")
        y -= 20
    if language_hint:
        c.drawString(50, y, f"Language Hint: {language_hint}")
        y -= 20

    y -= 10
    c.setFont("Helvetica-Bold", 12)
    c.drawString(50, y, "Applicant Details")

    details = [
        ("Full Name", fields.get("full_name") or "N/A"),
        ("Date of Birth", fields.get("date_of_birth") or "N/A"),
        ("Address", fields.get("address") or "N/A"),
        ("ID Number", fields.get("id_number") or "N/A"),
        ("Document Type", fields.get("document_type") or "N/A"),
    ]

    y -= 25
    c.setFont("Helvetica", 11)
    for label, value in details:
        c.drawString(50, y, f"{label}: {value}")
        y -= 20

    y -= 20
    c.setFont("Helvetica-Oblique", 10)
    c.drawString(50, y, "Auto-generated by CIVIC.AI backend. Verify details before submission.")

    c.showPage()
    c.save()
    return output_path
